baseURL = 'https://filippo-orru.com/'
languageCode = 'en-us'
title = 'Filippo Orru'
theme = 'hugo-coder'

[params]
author = 'Filippo Orru'
description = "John Doe's personal website"
keywords = 'blog,developer,personal'
info = ['Full Stack Wizard âœ¨']
colorScheme = "dark"
avatarURL = "images/avatar.png"
featuredPage = "/projects/four-in-a-row"

[taxonomies]
category = "categories"
series = "series"

[[languages.en.menu.main]]
name = "About me"
weight = 2
url = "about-me"

[[languages.en.menu.main]]
name = "Projects"
weight = 1
url = "projects/"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/ffactory-ofcl/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/filippo-orru/"